services:
  fluent-bit:
    container_name: fluent-bit
    image: fluent/fluent-bit:latest

    volumes:
      - ./configuration/fluentbit:/fluent-bit/etc
      # Вставить путь до проекта pom_mmwave_vital_signs
      - /home/gamkere/code-project/python-project/pom_mmwave_vital_signs/data/radar:/log-pom
  
  kafka1:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka1:9093
      # listners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_RAFT_CLUSTER_ID=kWWC-f6_R7maB4uCGgaTxA
    
    volumes:
      - volume1:/bitnami/kafka

  ui:
    image: provectuslabs/kafka-ui:v0.4.0
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka1:9092
      - KAFKA_CLUSTERS_0_NAME=kraft
    
  clickhouse:
    image: bitnami/clickhouse:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '8123:8123'

    volumes:
      - volume2:/bitnami/kafka

volumes:
  volume1:
  volume2: